version: '3'

services:
  server:
    container_name: node-api-recipes
    build: '.'
    volumes:
      - ./:/node-app
      - ./node_modules:/node-app/node_modules
    environment:
      NODE_ENV: development
    ports:
      - '3001:3001'